# Generated by Django 5.0.6 on 2024-07-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_order_billing_shipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.CharField(default='', max_length=255),
        ),
    ]
