# Generated by Django 5.0.6 on 2024-07-16 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_cart_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='size',
        ),
    ]
