# Generated by Django 5.0.6 on 2024-07-23 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='saler_reg',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
